version: '3'

services:

  python-container:
    image: bpmbee/cloudflare-dns-updater:latest # or :distroless
    environment:
      - HOST=example.com,another.example.com
      - TOKEN=YOURCLOUDFLARETOKEN
      - TIMEOUT=60
    restart: unless-stopped
